### ISSUE TITLE
Server info command fails if `manage_guild` and `ban_members` permissions are not present.

### ISSUE THREAD

**Issue by parafoxia** [sgoudham/Enso-Bot#7]
https://github.com/sgoudham/Enso-Bot/blob/a75c5be078554898bd80b4cc34b50a8fd3d64fb5/cogs/info.py#L205
https://github.com/sgoudham/Enso-Bot/blob/a75c5be078554898bd80b4cc34b50a8fd3d64fb5/cogs/info.py#L265-L266
https://github.com/sgoudham/Enso-Bot/blob/a75c5be078554898bd80b4cc34b50a8fd3d64fb5/cogs/info.py#L267-L268

The check on line 205 should be replaced with individual `ctx.guild.guild_permissions` checks above lines 266 and 268.

This will allow the command to run even if the bot does not have those permissions.

**Comment by sgoudham** [comment]
Ahhh great thinking! Will be sure to implement it!
